site_name: "JD Tech Notes"
site_description: "My Quick Reference Docs"
site_author: "J.D. Birla"
site_url: "https://jdbirla-dev-notes.netlify.app/"

# Repository
repo_name: "jdbirla/jd-dev-notes"
repo_url: "https://github.com/jdbirla/jd-dev-notes"

# Copyright
copyright: "Copyright &copy; 2020 - 2023 J.D. Birla"

theme:
  name: material
nav:
  - Home: index.md
  - RunningNotes: runningnotes.md
  - Learning: learning.md
  - JDIdeas: jdideas.md
  - AI Tools: aitools.md
  - Shortcuts: shortcuts.md
  - Common_Abbreviations: CommonAbbreviations.md
  - BackEnd:
    - Java:
      - Ecosystem: java/ecosystem.md
      - Maven: java/maven.md
      - Gradle: java/gradle.md
      - JavaJdGuide: java/javajdguide.md
    - SpringBoot:
      - Introduction: springboot/introduction.md
      - spring-security-jwt: springboot/spring-security-jwt.md
    - JPA_Hibernate:
      - jpa_guide: springboot/jpaguide.md
      - jpa_performance: springboot/jpaperformance.md
    - Testing:
      - Testing_Guide: testing/testing_guide.md
  - FrontEnd:
    - TypeScript:
      - Introduction: typescript/introduction.md
    - HTML_CSS: frontend/html_css.md
    - JavaScript: frontend/javascript.md
    - React: frontend/react.md
    - Java-javascript: frontend/java-javascript.md
    - Frontend-Interview: frontend/Frontend-Interview.md
  - DevOps:
    - Tools: devops/devops.md
    - Linux:
      - Linux: devops/linux.md
      - Linux-cs: devops/linuxcs.md
    - Docker:
      - Docker: devops/docker.md
      - Docker_CS: devops/dockercs.md
    - Ansible: devops/ansible.md
    - Terraform: devops/terraform.md
    - AWS: devops/aws.md
    - Kubernetes_CS: devops/kubernetescs.md
    - FSP_Deployment: devops/FSP_Deployment.md
  - Tools:
    - IDE:
      - Intellij: tools/intellij.md
      - VSCode: tools/vscode.md
  - Misc:
    - CleanArchitecture: misc/clean-architecture.md
    - Agile: misc/agile.md
    - Daily_Commands: misc/Daily_Commands.md
# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/jdbirla"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/jdbirla/"

# Extensions
markdown_extensions:
  - codehilite
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
