---
site_name: JD Tech Notes
site_description: My Quick Reference Docs
site_author: J.D. Birla
site_url: https://jdbirla-dev-notes.netlify.app/
repo_name: jdbirla/jd-dev-notes
repo_url: https://github.com/jdbirla/jd-dev-notes
copyright: Copyright &copy; 2020 - 2023 J.D. Birla
theme:
  name: material
nav:
  - Home: index.md
  - Learning: learning.md
  - AI Tools: aitools.md
  - Shortcuts: shortcuts.md
  - BackEnd:
      - Java:
          - Ecosystem: java/ecosystem.md
          - Maven: java/maven.md
          - Gradle: java/gradle.md
      - SpringBoot:
          - Introduction: springboot/introduction.md
  - FrontEnd:
      - TypeScript:
          - Introduction: typescript/introduction.md
  - DevOps:
      - Tools: devops/devops.md
      - Linux:
          - Linux: devops/linux.md
          - Linux-cs: devops/linuxcs.md
      - Docker:
          - Docker: devops/docker.md
          - Docker CS: devops/dockercs.md
      - Ansible: devops/ansible.md
      - Terraform: devops/terraform.md
      - AWS: devops/aws.md
      - Kubernetes-cs: devops/kubernetescs.md
  - Tools:
      - IDE:
          - Intellij: tools/intellij.md
  - Misc:
      - CleanArchitecture: misc/clean-architecture.md
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jdbirla
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jdbirla/
markdown_extensions:
  - codehilite
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: ""
      emoji_generator: ""
